using System.Text;
using Microsoft.CodeAnalysis;

namespace AvaloniaApplication.SourceGenerators.Extensions;

public static class StringBuilderExtensions
{
    extension(StringBuilder)
    {
        public static StringBuilder CreateSourceCode(INamespaceSymbol namespaceSymbol)
        {
            StringBuilder sourceCodeBuilder = new("""
                                                  // <auto-generated/>

                                                  #nullable enable


                                                  """);
            if (!namespaceSymbol.IsGlobalNamespace)
            {
                sourceCodeBuilder.AppendLine($"""
                                              namespace {namespaceSymbol.ToDisplayString()};

                                              """);
            }
            return sourceCodeBuilder;
        }
    }
}
